### ISSUE TITLE
개발 환경 설정

### ISSUE THREAD

**Issue by hanseulhee** [My-Pack/MyPack-Web#1]
## Description

- 개발 환경을 설정합니다

## Task

- [x] 파일 구조 세팅
- [x] 패키지 설치
- [x] eslint, prettier 설정
- [x] Github template 설정
- [x] Codeowner 설정
